apiVersion: v1
kind: Pod
metadata:
  name: data-setup
spec:
  containers:
    - name: data-setup
      image: quay.io/rhn_consulting_kemori/data-setup
      volumeMounts:
        - mountPath: "/app/data"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: demo-strage-claim
  imagePullSecrets:
    - name: quayio