apiVersion: batch/v1
kind: Job
metadata:
  name: insert-table-job
  namespace: demo-report
  labels:
    app: insert-table-app
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: insert-table-app
          image: quay.io/rhn_consulting_kemori/insert_table:latest
          imagePullPolicy: Always
          env:
            - name: DB_USER
              value: "test"
            - name: DB_PASSWORD
              value: "test"
            - name: DB_SERVERNAME
              value: "postgresql.demo-report.svc.cluster.local"
            - name: DB_PORTNUMBER
              value: "5432"
